server:
  port: ${PORT:8190}
  servlet.context-path: /

spring:
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: info, health
  endpoint:
    health:
      enabled: true
      group.alive.include: ping
    info:
      enabled: true

logging.config: classpath:logback-spring-local.xml
  
message.topic.name: baeldung
long.message.topic.name: longMessage
greeting.topic.name: greeting
filtered.topic.name: filtered
partitioned.topic.name: partitioned
multi.type.topic.name: multitype
# monitoring - lag analysis
monitor.kafka.bootstrap.config: localhost:9092
monitor.kafka.consumer.groupid: baeldungGrp
monitor.topic.name: baeldung
# monitoring - simulation
monitor.producer.simulate: true
monitor.consumer.simulate: true
monitor.kafka.consumer.groupid.simulate: baeldungGrpSimulate
test.topic: testtopic1

